### ISSUE TITLE
Typing `hre` in the hardhat console hangs up the process

### ISSUE THREAD

**Issue by abarmat** [graphprotocol/contracts#559] opened 2022-04-08 19:06 UTC

**Comment by pcarranzav** [comment] 2022-04-11 16:22
Possibly caused by: https://github.com/NomicFoundation/hardhat/issues/1473

(There's a lazyObject in gre.ts)

**Comment by pcarranzav** [comment] 2022-04-13 19:18
Looked into it a bit more. It seems that there's two things causing this:

https://github.com/graphprotocol/contracts/blob/dev/hardhat.config.ts#L20

```
import '@tenderly/hardhat-tenderly'
```

And:

https://github.com/graphprotocol/contracts/blob/dev/tasks/contracts/functions.ts#L5

```
import 'hardhat-storage-layout'
```

Both of these dependencies follow the pattern from the hardhat issue mentioned above. I've confirmed that removing those lines and commenting out the code that depends on them resolves the problem. So the way forward would be to fix the issue on the hardhat side.

**Comment by pcarranzav** [comment] 2022-04-13 21:39
Trying to fix this in https://github.com/NomicFoundation/hardhat/pull/2608 - if that PR gets merged we should be able to fix this by bumping hardhat to the latest version.

**Closed** 2022-05-17 17:20 UTC
